compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPreapprovedPackages:
  - '@expo/cli@57.0.20'
  - '@expo/config-plugins@57.0.9'
  - '@expo/config@57.0.9'
  - '@expo/dom-webview@57.0.1'
  - '@expo/devtools@57.0.1'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/local-build-cache-provider@57.0.8'
  - '@expo/log-box@57.0.4'
  - '@expo/metro@56.0.2'
  - '@expo/metro-config@57.0.12'
  - 'babel-preset-expo@57.0.9'
  - 'expo@57.0.18'
  - 'expo-asset@57.0.15'
  - 'expo-constants@57.0.16'
  - 'expo-file-system@57.0.6'
  - 'expo-font@57.0.2'
  - 'expo-keep-awake@57.0.1'
  - 'expo-splash-screen@57.0.8'
  - 'react-native@0.86.3'

yarnPath: .yarn/releases/yarn-4.18.0.cjs
