name: Coverage
on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Coverage 🧪
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          package-manager: yarn
          threshold: 100
